trigger:
	- main

pool:
	vmImage: 'windows-latest'

variables:
	MySqlHost: '$(AZURE_MYSQL_HOST)'
	MySqlPort: '3306'
	MySqlDatabase: 'hospital_management'
	MySqlUser: '$(AZURE_MYSQL_USER)'
	MySqlPassword: '$(AZURE_MYSQL_PASSWORD)'

steps:
	- task: UseDotNet@2
		inputs:
			packageType: 'sdk'
			version: '9.0.x'

	- task: NodeTool@0
		inputs:
			versionSpec: '18.x'

	- script: |
			pwsh -NoLogo -NoProfile -Command "`$params = @{ MySqlHost='$(MySqlHost)'; MySqlPort=$(MySqlPort); MySqlDatabase='$(MySqlDatabase)'; MySqlUser='$(MySqlUser)'; MySqlPassword='$(MySqlPassword)'}; .\run-local-tests.ps1 @params"
		displayName: 'Run Azure-only tests (schema/seed + integration + API + frontend)'

	- task: PublishTestResults@2
		displayName: 'Publish backend integration test results'
		inputs:
			testResultsFormat: 'VSTest'
			testResultsFiles: 'reports/test-runs/unit/*.trx'
			failTaskOnFailedTests: true

	- task: PublishTestResults@2
		displayName: 'Publish API (Postman) test results'
		inputs:
			testResultsFormat: 'JUnit'
			testResultsFiles: 'reports/test-runs/api/results.xml'
			failTaskOnFailedTests: true

	- task: PublishTestResults@2
		displayName: 'Publish frontend (Jest) test results'
		inputs:
			testResultsFormat: 'JUnit'
			testResultsFiles: 'reports/test-runs/frontend/junit.xml'
			failTaskOnFailedTests: true

